### ISSUE TITLE
Loss of Equation 9 in code

### ISSUE THREAD

**Issue by jingyang2017** [zhirongw/lemniscate.pytorch#11]
Thanks for sharing the code. 
I did not find the loss of Eq(9) (the later part which makes feature representation of iteration t to be similar to that from iteration t-1 )in code. Is it not important?

**Comment by Eddiesyn** [comment]
Same confusion here... Hope could get an answer.

**Comment by TsungWeiTsai** [comment]
It seems that they are doing the momentum update of the memory bank instead of the proximal regularization (Eq9). You can reference the momentum update in backward function in NCEAverage.py. It would be great if the author can provide additional explanations for this.

**Comment by zhirongw** [comment]
Hi All, due to various reasons for maintaining the version of the code, there is such a mismatch between the paper and the code. Sorry for the confusion.

However, the loss in Eq(9) and the code in the momentum update is equivalent. (as explained by @TsungWeiTsai). To see this, the gradient (the change of the update) of the slots in the memory bank is in the direction of (v - v_{memory}) for both the loss signal in Eq (9) and the momentum update.

Therefore, the role of loss weight in Eq(9) and the parameter nce-m in momentum update are similar. Because of the momentum update is more intuitive and easier to tune, we release the code in this setting.
